/**
 * Solar Explorer — CelestialBody game object.
 *
 * A Phaser image whose texture is procedurally generated by BodyRenderer.
 * Handles its own pointer interaction and reports selection by id.
 */
import Phaser from 'phaser';
import type { BodyData } from '../../logic/library';
import { bodyRadiusPx } from '../../logic/scale';
import { BodyType, SPACECRAFT_RADIUS_PX } from '../../constants/constants';
import {
  resolveBodyVisual,
  drawCelestialBody,
  drawSmallBody,
} from '../renderers/BodyRenderer';
import { bodyHitRadiusPx, isTapGesture } from '../../logic/pointerInput';

/** Padding factor so rings and comet tails fit inside the texture canvas. */
const TEXTURE_PAD = 6;
const MIN_TEXTURE_SIZE = 12;

export type SelectHandler = (id: string) => void;

function isSmallBody(type: string): boolean {
  return type === BodyType.ASTEROID || type === BodyType.COMET;
}

/** Build (once) and return the procedural texture key for a body. */
export function ensureBodyTexture(
  scene: Phaser.Scene,
  body: BodyData,
): { key: string; radius: number } {
  const visual = resolveBodyVisual(body.id, body.type);
  const small = isSmallBody(body.type);
  const radius = small
    ? Math.max(SPACECRAFT_RADIUS_PX, 5)
    : bodyRadiusPx(body.radius_km);
  const key = `body:${body.id}`;

  if (!scene.textures.exists(key)) {
    const size = Math.ceil(Math.max(radius * TEXTURE_PAD, MIN_TEXTURE_SIZE));
    const texture = scene.textures.createCanvas(key, size, size);
    if (texture) {
      const ctx = texture.getContext();
      const center = size / 2;
      if (small) drawSmallBody(ctx, center, center, radius, body.id, visual);
      else drawCelestialBody(ctx, center, center, radius, body.id, visual);
      texture.refresh();
    }
  }
  return { key, radius };
}

export class CelestialBody extends Phaser.GameObjects.Image {
  readonly bodyId: string;
  readonly renderedRadius: number;

  constructor(scene: Phaser.Scene, body: BodyData, onSelect: SelectHandler) {
    const { key, radius } = ensureBodyTexture(scene, body);
    super(scene, 0, 0, key);
    this.bodyId = body.id;
    this.renderedRadius = radius;
    scene.add.existing(this);

    const hit = new Phaser.Geom.Circle(
      this.width / 2,
      this.height / 2,
      bodyHitRadiusPx(radius),
    );
    this.setInteractive(hit, Phaser.Geom.Circle.Contains);
    // Select on release, not press, and only when the gesture was a tap — a
    // press that travels is a pan/pinch and must not open this body's info.
    this.on('pointerup', (pointer: Phaser.Input.Pointer, _x: number, _y: number, event: Phaser.Types.Input.EventData) => {
      if (!isTapGesture(pointer.getDistance())) return;
      event.stopPropagation();
      onSelect(body.id);
    });
  }
}
